import { createServerFeature } from '@payloadcms/richtext-lexical'

/**
 * Server-side wrapper for WordTablePasteFeatureClient.
 *
 * Payload Lexical features must be declared on the server config; the
 * `ClientFeature` path string is resolved through the admin importMap
 * (auto-generated by `pnpm payload generate:importmap`).
 */
export const WordTablePasteFeature = createServerFeature({
  feature: {
    ClientFeature:
      '@/lexical/features/wordTablePaste/feature.client#WordTablePasteFeatureClient',
  },
  key: 'wordTablePaste',
})
