import type { CollectionConfig } from 'payload'
import { lexicalEditor } from '@payloadcms/richtext-lexical'

export const Posts: CollectionConfig = {
  slug: 'posts',
    admin: {
        useAsTitle: 'title',
            defaultColumns: ['title', 'publishedDate', 'status', 'updatedAt'],
                group: '콘텐츠',
                  },
                    access: {
                        read: () => true,
                          },
                            versions: {
                                drafts: true,
                                  },
                                    fields: [
                                        {
                                              name: 'title',
                                                    type: 'text',
                                                          label: '제목',
                                                                localized: true,
                                                                      required: true,
                                                                          },
                                                                              {
                                                                                    name: 'excerpt',
                                                                                          type: 'textarea',
                                                                                                label: '요약 (Excerpt)',
                                                                                                      localized: true,
                                                                                                          },
                                                                                                              {
                                                                                                                    name: 'thumbnail',
                                                                                                                          type: 'upload' as const,
                                                                                                                                label: '썸네일 이미지',
                                                                                                                                      relationTo: 'media',
                                                                                                                                          },
                                                                                                                                              {
                                                                                                                                                    name: 'content',
                                                                                                                                                          type: 'richText',
                                                                                                                                                                label: '본문',
                                                                                                                                                                      localized: true,
                                                                                                                                                                            editor: lexicalEditor(),
                                                                                                                                                                                },
                                                                                                                                                                                    {
                                                                                                                                                                                          name: 'tags',
                                                                                                                                                                                                type: 'relationship',
                                                                                                                                                                                                      label: '태그',
                                                                                                                                                                                                            relationTo: 'tags',
                                                                                                                                                                                                                  hasMany: true,
                                                                                                                                                                                                                      },
                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                name: 'publishedDate',
                                                                                                                                                                                                                                      type: 'date',
                                                                                                                                                                                                                                            label: '발행일',
                                                                                                                                                                                                                                                  admin: {
                                                                                                                                                                                                                                                          date: { pickerAppearance: 'dayAndTime' },
                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                              name: 'status',
                                                                                                                                                                                                                                                                                    type: 'select',
                                                                                                                                                                                                                                                                                          label: '상태',
                                                                                                                                                                                                                                                                                                defaultValue: 'draft',
                                                                                                                                                                                                                                                                                                      options: [
                                                                                                                                                                                                                                                                                                              { label: '초안 (Draft)', value: 'draft' },
                                                                                                                                                                                                                                                                                                                      { label: '발행됨 (Published)', value: 'published' },
                                                                                                                                                                                                                                                                                                                              { label: '보관됨 (Archived)', value: 'archived' },
                                                                                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                                                                                          admin: { position: 'sidebar' },
                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                  {
                                                                                                                                                                                                                                                                                                                                                        name: 'publishedLocales',
                                                                                                                                                                                                                                                                                                                                                              type: 'select',
                                                                                                                                                                                                                                                                                                                                                                    label: '공개 언어',
                                                                                                                                                                                                                                                                                                                                                                          hasMany: true,
                                                                                                                                                                                                                                                                                                                                                                                options: [
                                                                                                                                                                                                                                                                                                                                                                                        { label: '한국어 (ko)', value: 'ko' },
                                                                                                                                                                                                                                                                                                                                                                                                { label: 'English (en)', value: 'en' },
                                                                                                                                                                                                                                                                                                                                                                                                        { label: 'Español (es)', value: 'es' },
                                                                                                                                                                                                                                                                                                                                                                                                                { label: 'Русский (ru)', value: 'ru' },
                                                                                                                                                                                                                                                                                                                                                                                                                        { label: 'Deutsch (de)', value: 'de' },
                                                                                                                                                                                                                                                                                                                                                                                                                                { label: 'Français (fr)', value: 'fr' },
                                                                                                                                                                                                                                                                                                                                                                                                                                        { label: '中文 (zh)', value: 'zh' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                { label: 'العربية (ar)', value: 'ar' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                      ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                            admin: { position: 'sidebar' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          name: 'aiGenerated',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                type: 'checkbox',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      label: 'AI 생성 콘텐츠',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            defaultValue: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  admin: { position: 'sidebar' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                name: 'translationStatus',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type: 'json',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            label: '번역 상태',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  admin: { position: 'sidebar' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                name: 'meta',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type: 'group',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            label: 'SEO 메타데이터',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fields: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          { name: 'metaTitle', type: 'text', label: '메타 제목', localized: true },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  { name: 'metaDescription', type: 'textarea', label: '메타 설명', localized: true },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          { name: 'ogImage', type: 'upload' as const, label: 'OG 이미지', relationTo: 'media' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              name: 'slug',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type: 'text',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          label: 'Slug (URL)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                required: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      unique: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            admin: { position: 'sidebar' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }